<a href="https://colab.research.google.com/github/Doladun1/PyTorch/blob/main/InitializingTensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
import torch

new_torch = torch.arange(12)
buff = new_torch
new_torch

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [41]:
new_torch = new_torch.reshape(4,3)
new_torch

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [42]:
buff_torch = buff.reshape(4,-1)
buff_torch

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [43]:
my_torch4 = torch.arange(15)
my_torch4

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [44]:
my_torch4 = my_torch4.reshape(3,-1)
my_torch4

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [45]:
my_torch4[:,0]
my_torch4[:,4]
my_torch4[:,3]
my_torch4[:,2]

tensor([ 2,  7, 12])

In [46]:
my_torch4[:,::2]

tensor([[ 0,  2,  4],
        [ 5,  7,  9],
        [10, 12, 14]])

In [47]:
my_torch4[1,4]

tensor(9)

In [48]:
my_torch4[1,:1]

tensor([5])